vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /avatars
            upload_destination: '%kernel.project_dir%/public/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
